export { default as AdSlot } from './Ads'
export { default as HeaderTitle } from './HeaderTitle'
export { default as Logo } from './Logo'
export { default as SocialMediaIcon } from './SocialMediaIcon'
export { default as VideoComp } from './VideoComp'
export { default as VideoThumbnail } from './VideoThumbnail'
